### ISSUE TITLE
Add screens/stages

### ISSUE THREAD

**Issue by Glusk2** [Glusk2/sprouts#95]
Currently the game doesn't have screens.

The stages are as follows:

- [x] 1. <del>Select starting points by tapping/clicking on a screen</del>

    <del>the first move signals the start of the game - no more points can be added.</del>
    Add starting points #46.
- [x] 2. Draw one or more moves:
    - [x] 2.1. draw a curve #104
    - [x] 2.2. add the center point #107
- [ ] 3. Undo one or more moves - dificult to implement. Canceling last action (either 2.1. or 2.2.) seems much simpler
- [x] 3. Detect the end of the game #148
- [x] 4. Clear the game; go to 1 #104.

**Comment by Glusk2** [comment]
Using LibGDX's [Game](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/Game.html)+[Screen](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/Screen.html) vs. cooking up something similar yourself.

**Comment by Glusk2** [comment]
Apparently LibGDX also has a concept of [Stage](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/Stage.html).

**Comment by Glusk2** [comment]
`Stage` can be used to layout UI `Actor`s.

The `Game` will only have one `Screen`. The drawing board will be rendered in *snapshots*.

A *snapshot* has:

- to know how to render itself
- respond to/handle user input

**Comment by Glusk2** [comment]
Won't implement full move undo. As of #104, the Move (the curve drawn) can be canceled until the middle sprout is added.
